development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: logistics
  username: root
  password:
test:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: logistics_test
  username: root
  password:
